name: Deploy to Firebase Hosting when pr to master 
'on':
  pull_request:
    branches:
      - master
jobs:
  build_and_deploy_web:
    name: Build Flutter web and deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1.5.1
      - run: flutter pub get
      - run: flutter build web

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KOALA_FINANCE }}'
          channelId: live
          projectId: koala-finance

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: web-build
          path: build/web
